language: node_js
node_js:
- node
install:
- cd $TRAVIS_BUILD_DIR/client && npm install
- cd $TRAVIS_BUILD_DIR/server && npm install
- npm install -g vsce
script:
- cd $TRAVIS_BUILD_DIR/client && npm run lint
- cd $TRAVIS_BUILD_DIR/server && npm run compile
- cd $TRAVIS_BUILD_DIR/client && vsce package
after_success:
- test -n $TRAVIS_TAG && test $TRAVIS_BRANCH='master' && cd $TRAVIS_BUILD_DIR/client
  && vsce publish -p $VSCODE_TOKEN
env:
  global:
    secure: hz5n6m1eASq/g3pGl3Cp5d5n3CCjk+JBupA6Oo+VmhBfupgMXJUogW1gt2opj+JeM4+aXGlNq6HEV/kB66lDo/Q8RXVnvzPtdqBJztK9kDWHcYtBjyTk5jKLf+0B2bny7hiaq9HuwphjJCUIrqBwZBa3e8Iz/A5eiRhR/apS2Li/MgXNGSVsPq/04Jbftm6yq9qBp3SfyTyw7FmY98ZTIvukDU7BkNzYf8wxtDvUZ3JRKpFbDa1aVeFyi0/JLFrCD+QnXUs0E9I3eJcd213QBj7HqSouQXis5tnU/iBvexAh3in0ftZwkZtLyxdiLcxcL4wx2xIIn225s2z/4t17hGISIiKZ9uLk7IxFNIcM2KegPQky8cGWycEs6SX+yryIxMFDNHNUTNqFNT7NpuRMqQ9MJ+1C0Lxbe7NSx/Vc2vIAi3znbmWfdsbx7p4WdjUQ1+dfmkerGzVLDK7y16Gz05wfVpOeBEXfQ8ROuyy5mmDQF7/XcQQ83BV2hY+0xvWQ+aGk4f2uuP+8pFnj1zVSd0I5qKfZMKIyE7dJZwYjMP83TrOIHuM8qwraPWZbmG2L6b//gxnViqYpCdxcOO4dB6F8Y0c0g/w3VAAOQHTqHcY3G4w/IFlOhDBfDFP2H1uoqaoubcuthWf37UCCfkC8v2VOVwcmBGEkmGy5U6tuvqo=
