language: node_js
node_js:
- node
install:
- cd $TRAVIS_BUILD_DIR/client && npm install
- cd $TRAVIS_BUILD_DIR/server && npm install
- npm install -g vsce
script:
- cd $TRAVIS_BUILD_DIR/client && npm run lint
- cd $TRAVIS_BUILD_DIR/server && npm run compile
- cd $TRAVIS_BUILD_DIR/client && vsce package
after_success:
- test -n $TRAVIS_TAG && test $TRAVIS_BRANCH='master' && cd $TRAVIS_BUILD_DIR/client && vsce publish -p $VSCODE_TOKEN
env:
  global:
    secure: gudbi4BIGSxuZIOgQ6kB4CFgJLX7bB5bh1daUh9pnONmNeDCdP/xCmXkJgOrckW1AkrSdHsvptrhpEmBb9/qiji1o3R9i5LP9VpnZdEael2qGlHSbAol05ZZsBWJX0s9o8AUcQRQ8d2og4woYtBPj3PSiPqrkxMPa15xkfvF86HRfHimOEYKyH2xaybd8MSeQ1gJIT0AKV/Q9kKKI6wbtKJJip3Dm3tKoXh041eK2JypLrYV1EtBJ3TF/ApiP2SxXUf0y/bJcyYOnsDznPf4Y/2VnjbDkVZaDOke7PDCFokE9ZClrqAmVs6pykccfbGq57mkzQfMM4aw7CDeCFZYaK26qZAaeQL92V041LFya3KaxpHtlsoqkzV3so4TtJ704iWLhDup8xFMV30bpzYUiIhC45rFZDb+cGmO0ZO3eOGJDKADI5XUOfSstGRBtNjaCgiXjuRNTVbbDeLuD5lvpHnBwPiaMmQh9AiBiRwli9HMcSva0Kf6+sezM94k9FnvVAKjdwUaXVltAW65yppXlCiEiemdECva0pZHvxJ+u89MhdujP6ZusO4Ny/Npkh1TVAar30pvlSOaYZ6PnGIo+61bIZUL9ggZ4myEQGpKay8S2Xy8hgoYnn+y15qyfcAHeeOkbcH88rUWENyk7R4jFBHCkxAMC9gO6bVGqfx1u1c=
