language: node_js
node_js:
- node
install:
- cd $TRAVIS_BUILD_DIR/client && npm install
- cd $TRAVIS_BUILD_DIR/server && npm install
- npm install -g vsce
script:
- cd $TRAVIS_BUILD_DIR/client && npm run lint
- cd $TRAVIS_BUILD_DIR/server && npm run compile
- cd $TRAVIS_BUILD_DIR/client && vsce package
after_success:
- test -n $TRAVIS_TAG && test $TRAVIS_BRANCH='master' && \
    cd $TRAVIS_BUILD_DIR/client && vsce publish -p $VSCODE_TOKEN
env:
  global:
  - secure: kLCQG+6Fxccz9Op+YODHsUHY57G/6qY7kWb3/Ka+nSnXDCbvhJU64ul3bJQFNOW1inJ6P6w120aQ9DtmrFB1Y2OwhJVL0el6FhgUmi3B0qiZK40NQ+XzXE9wStI+SPdLDygkPb8vGBLlAZaSk27V0vcz4vd2u8G0oZ4S2Khkbv3RYxCoJjdISxfGhBk8FLb4OFy9NkxiFkAePjZQlWUSvi8mDYnarq8Aqm4wBpcuFoUlNmZbzs1mQSZb02yKQqhctvcrJEitnq7rfJcxxfTysbxc0zVQ7Ml2V+YzEP2V8CDRsEykF/hQpCGMISLgjXiOJ6pe82Ll5jVmH48/MK5Xg1q6MDWhUVHB52flkd4Iy4GYnnSDF8t4rO+yEm53IWY/wIH895z+1eHuCrLuieZjmt45CVD3LESCaJiG9/6/QwXOlAH2OGm5znplg6+FbAwlabOMPbpimuqTFshcrs9YW9Eef7h/BFZmDpQwAuSo9QtZ75s4AgDdjZQ1NGhBiSXU1GpM+otUmkCqCiDd9tIAN1FjGGBiUu3lLdpswriWOdF5LS8OTQq/GJr3WO9+8eooEvbAVk0v9Oq3j9irNdWPM2ZWVLYglcVVA/5azUP/iKKdRUmA2aaqonV7BxNBoqfnNVK6JDdQuPVs4uzPTMksjBLIwtgsGwViTTllT+ggDEM=
